app = "spark-evaluate"
primary_region = "cdg"

[env]
  SENTRY_ENVIRONMENT = "production"

[deploy]
  strategy = "rolling"

[mount]
  source = "spark-evaluate-data"
  destination = "/var/lib/spark-evaluate/"